export type MenuPriority = 'P0' | 'P1' | 'P2' | 'P3' | 'P4';

export type ImplementedViewKey =
  | 'dashboard'
  | 'orders'
  | 'reviews'
  | 'dispenses'
  | 'dispensePrint'
  | 'rechecks'
  | 'recheckScan'
  | 'decoction'
  | 'logistics'
  | 'logisticsInfo'
  | 'logisticsUnreceivedFollowups'
  | 'logisticsPrint'
  | 'logisticsSpecialRules'
  | 'logisticsAddressCosts'
  | 'logisticsMerges'
  | 'exceptionLogs'
  | 'labelTemplates'
  | 'labelPrints'
  | 'smsTemplates'
  | 'smsSendSingle'
  | 'smsRecords'
  | 'portal'
  | 'institutionList'
  | 'institutionApps'
  | 'institutionIpWhitelist'
  | 'institutionApis'
  | 'institutionApiPermissions'
  | 'reports'
  | 'auditPerformance'
  | 'auditPerformanceDetails'
  | 'decoctionPerformance'
  | 'decoctionPerformanceDetails'
  | 'dispensePerformance'
  | 'dispensePerformanceDetails'
  | 'herbDosage'
  | 'institutionHerbReconciliation'
  | 'logisticsPerformance'
  | 'logisticsPerformanceDetails'
  | 'prescriptionHerbDetails'
  | 'recheckPerformance'
  | 'recheckPerformanceDetails'
  | 'institutionPrescriptionCounts'
  | 'prescriptionReconciliation'
  | 'integration'
  | 'observability'
  | 'ops'
  | 'problemRegistrations'
  | 'operatorManage'
  | 'menuRegistry'
  | 'settingDicts'
  | 'settingSystemConfigs'
  | 'settingDecoctCenters'
  | 'drugHerbs'
  | 'drugHerbAreas'
  | 'drugHerbIndexes'
  | 'drugIndexOperationLogs'
  | 'addressModify'
  | 'prescriptionModify'
  | 'orderManageAction'
  | 'prescriptionReprint'
  | 'manualProcess'
  | 'orderWarehouse'
  | 'orderInterceptRules'
  | 'orderReceipt';

export interface AppRouteItem {
  key: string;
  label: string;
  group: string;
  path: string;
  legacyRoute: string | null;
  priority: MenuPriority;
  implemented: boolean;
  subtitle: string;
  componentKey?: ImplementedViewKey;
  showCount?: boolean;
  plannedComponent: string;
  coreActions: readonly string[];
  apiDependencies: readonly string[];
}

export interface MenuItem extends AppRouteItem {
  legacyRoute: string;
}

export interface ViewTitle {
  title: string;
  subtitle: string;
}

export const standaloneRouteItems = [
  {
    key: 'dashboard',
    label: '工作台',
    group: '系统入口',
    path: '/dashboard',
    legacyRoute: null,
    priority: 'P0',
    implemented: true,
    subtitle: '查看核心待处理事项和系统健康概览',
    componentKey: 'dashboard',
    plannedComponent: 'features/dashboard/DashboardHome.vue',
    coreActions: ['待办概览', '系统健康概览'],
    apiDependencies: ['订单概览', '工作流待办', '服务健康状态'],
  },
  {
    key: 'portal',
    label: '门户查单',
    group: '系统入口',
    path: '/portal/lookup',
    legacyRoute: null,
    priority: 'P0',
    implemented: true,
    subtitle: '医院查单和地址补录申请',
    componentKey: 'portal',
    plannedComponent: 'features/portal/PortalLookup.vue',
    coreActions: ['医院查单', '处方详情查询', '地址补录申请'],
    apiDependencies: ['门户订单查询', '地址补录申请'],
  },
  {
    key: 'integration',
    label: '集成任务',
    group: '系统入口',
    path: '/integration/messages',
    legacyRoute: null,
    priority: 'P0',
    implemented: true,
    subtitle: '外围消息、地址回推和重试任务',
    componentKey: 'integration',
    plannedComponent: 'features/integration/IntegrationConsole.vue',
    coreActions: ['消息查询', '地址回推', '失败重试'],
    apiDependencies: ['外部消息', '地址回调', '重试任务'],
  },
] as const satisfies readonly AppRouteItem[];

export const menuItems = [
  {
    key: 'systemUsers',
    label: '用户管理',
    group: '系统管理',
    path: '/system/users',
    legacyRoute: 'user.html',
    priority: 'P4',
    implemented: true,
    subtitle: '后台操作人员账号、角色标识和启停状态维护',
    componentKey: 'operatorManage',
    showCount: true,
    plannedComponent: 'features/settings/OperatorManage.vue',
    coreActions: ['列表', '筛选', '新增', '编辑', '启停'],
    apiDependencies: ['操作员工号 CRUD'],
  },
  {
    key: 'systemRoles',
    label: '角色管理',
    group: '系统管理',
    path: '/system/roles',
    legacyRoute: 'role.html',
    priority: 'P4',
    implemented: false,
    subtitle: '角色维护和权限分配',
    plannedComponent: 'features/system/RoleManage.vue',
    coreActions: ['列表', '新增', '编辑', '删除', '角色授权'],
    apiDependencies: ['角色 CRUD', '菜单树', '权限点', '操作审计'],
  },
  {
    key: 'systemMenus',
    label: '菜单管理',
    group: '系统管理',
    path: '/system/menus',
    legacyRoute: 'menu.html',
    priority: 'P4',
    implemented: true,
    subtitle: '前端菜单入口、路径、旧路由和接入状态核对',
    componentKey: 'menuRegistry',
    showCount: true,
    plannedComponent: 'features/system/MenuRegistry.vue',
    coreActions: ['菜单树', '筛选', '路径核对', '接入状态核对'],
    apiDependencies: ['前端菜单注册表'],
  },
  {
    key: 'settingDicts',
    label: '字典列表',
    group: '参数管理',
    path: '/settings/dicts',
    legacyRoute: 'systemSetting/listDict.html',
    priority: 'P3',
    implemented: true,
    subtitle: '字典项、状态枚举和业务配置',
    componentKey: 'settingDicts',
    showCount: true,
    plannedComponent: 'features/settings/DictList.vue',
    coreActions: ['列表', '筛选', '新增', '编辑', '删除', '启停'],
    apiDependencies: ['字典类型', '字典项 CRUD', '缓存刷新'],
  },
  {
    key: 'settingSystemConfigs',
    label: '参数配置',
    group: '参数管理',
    path: '/settings/system-configs',
    legacyRoute: 'systemSetting/listSystemConfig.html',
    priority: 'P3',
    implemented: true,
    subtitle: '系统参数查询、编辑和缓存刷新',
    componentKey: 'settingSystemConfigs',
    showCount: true,
    plannedComponent: 'features/settings/SystemConfig.vue',
    coreActions: ['参数列表', '编辑', '启停', '刷新缓存'],
    apiDependencies: ['参数查询', '参数保存', '缓存刷新', '操作审计'],
  },
  {
    key: 'settingDecoctCenters',
    label: '煎煮中心配置',
    group: '参数管理',
    path: '/settings/decoct-centers',
    legacyRoute: 'systemSetting/listDecoctCenter.html',
    priority: 'P3',
    implemented: true,
    subtitle: '煎煮中心基础配置维护',
    componentKey: 'settingDecoctCenters',
    showCount: true,
    plannedComponent: 'features/settings/DecoctCenterConfig.vue',
    coreActions: ['列表', '新增', '编辑', '删除'],
    apiDependencies: ['煎煮中心 CRUD'],
  },
  {
    key: 'settingOperators',
    label: '工号管理',
    group: '参数管理',
    path: '/settings/operators',
    legacyRoute: 'systemSetting/listOperUser.html',
    priority: 'P3',
    implemented: true,
    subtitle: '生产工号和作业人员维护',
    componentKey: 'operatorManage',
    showCount: true,
    plannedComponent: 'features/settings/OperatorManage.vue',
    coreActions: ['工号列表', '新增', '编辑', '启停'],
    apiDependencies: ['操作员工号 CRUD', '作业类型'],
  },
  {
    key: 'institutionList',
    label: '机构列表',
    group: '机构管理',
    path: '/institutions',
    legacyRoute: 'mechanism/listInstitutions.html',
    priority: 'P3',
    implemented: true,
    subtitle: '医院/机构档案和接口接入身份维护',
    componentKey: 'institutionList',
    showCount: true,
    plannedComponent: 'features/institution/InstitutionList.vue',
    coreActions: ['列表', '筛选', '新增', '编辑', '启停'],
    apiDependencies: ['机构 CRUD', '回调配置', '操作审计'],
  },
  {
    key: 'institutionApps',
    label: '机构应用配置',
    group: '机构管理',
    path: '/institutions/apps',
    legacyRoute: 'mechanism/listInstitutions.html',
    priority: 'P3',
    implemented: true,
    subtitle: '机构 AppKey、签名密钥和回调地址维护',
    componentKey: 'institutionApps',
    showCount: true,
    plannedComponent: 'features/institution/InstitutionApps.vue',
    coreActions: ['应用列表', '新增', '编辑', '启停', '重置密钥'],
    apiDependencies: ['机构应用 CRUD', '机构列表'],
  },
  {
    key: 'institutionIpWhitelist',
    label: '机构 IP 白名单列表',
    group: '机构管理',
    path: '/institutions/ip-whitelist',
    legacyRoute: 'mechanism/listWhiteIp.html',
    priority: 'P3',
    implemented: true,
    subtitle: '调用来源 IP 管控',
    componentKey: 'institutionIpWhitelist',
    showCount: true,
    plannedComponent: 'features/institution/IpWhitelist.vue',
    coreActions: ['白名单列表', '新增', '编辑', '启停'],
    apiDependencies: ['IP 白名单 CRUD', '访问日志'],
  },
  {
    key: 'institutionApis',
    label: '接口列表',
    group: '机构管理',
    path: '/institutions/apis',
    legacyRoute: 'mechanism/listApiInfo.html',
    priority: 'P3',
    implemented: true,
    subtitle: '外部 API 方法定义维护',
    componentKey: 'institutionApis',
    showCount: true,
    plannedComponent: 'features/institution/ApiInfoList.vue',
    coreActions: ['API 定义列表', '新增', '编辑', '启停'],
    apiDependencies: ['API 定义 CRUD'],
  },
  {
    key: 'institutionApiPermissions',
    label: '机构接口权限列表',
    group: '机构管理',
    path: '/institutions/api-permissions',
    legacyRoute: 'mechanism/listApiPermission.html',
    priority: 'P3',
    implemented: true,
    subtitle: '机构 API 授权与接入控制',
    componentKey: 'institutionApiPermissions',
    showCount: true,
    plannedComponent: 'features/institution/ApiPermissionList.vue',
    coreActions: ['按机构授权接口', '刷新缓存'],
    apiDependencies: ['机构列表', 'API 列表', '授权保存', '网关缓存刷新'],
  },
  {
    key: 'logisticsSpecialRules',
    label: '机构物流费规则配置',
    group: '物流管理',
    path: '/logistics/special-rules',
    legacyRoute: 'logistics/listLogisSpecial.html',
    priority: 'P2',
    implemented: true,
    subtitle: '机构维度物流计费规则配置',
    componentKey: 'logisticsSpecialRules',
    showCount: true,
    plannedComponent: 'features/logistics/LogisSpecialRule.vue',
    coreActions: ['规则列表', '新增', '编辑', '删除'],
    apiDependencies: ['物流费用规则 CRUD', '操作审计'],
  },
  {
    key: 'logisticsAddressCosts',
    label: '机构地址物流费配置',
    group: '物流管理',
    path: '/logistics/address-costs',
    legacyRoute: 'logistics/listLogisCompanycostAddr.html',
    priority: 'P2',
    implemented: true,
    subtitle: '地址维度物流费用维护',
    componentKey: 'logisticsAddressCosts',
    showCount: true,
    plannedComponent: 'features/logistics/AddressCost.vue',
    coreActions: ['地址费用列表', '新增', '编辑', '导入', '导出'],
    apiDependencies: ['地址费用 CRUD', '导入任务', '导出任务'],
  },
  {
    key: 'logistics',
    label: '订单发货查询',
    group: '物流管理',
    path: '/logistics/deliveries',
    legacyRoute: 'logistics/listLogisDelivery.html',
    priority: 'P1',
    implemented: true,
    subtitle: '处理待发货、发货、签收和回调补偿',
    componentKey: 'logistics',
    showCount: true,
    plannedComponent: 'features/logistics/LogisticsFulfillment.vue',
    coreActions: ['发货查询', '打包发货', '发货/签收', '轨迹补录'],
    apiDependencies: ['待发货查询', '物流单查询', '打包', '发货', '签收', '轨迹查询'],
  },
  {
    key: 'logisticsTraces',
    label: '物流信息查询',
    group: '物流管理',
    path: '/logistics/traces',
    legacyRoute: 'logistics/listLogisInfo.html',
    priority: 'P2',
    implemented: true,
    subtitle: '运单和物流轨迹查询',
    componentKey: 'logisticsInfo',
    plannedComponent: 'features/logistics/LogisticsInfo.vue',
    coreActions: ['运单查询', '轨迹查询', '签收状态查询'],
    apiDependencies: ['物流单查询', '轨迹查询'],
  },
  {
    key: 'logisticsPrint',
    label: '物流打单',
    group: '物流管理',
    path: '/logistics/print',
    legacyRoute: 'logistics/logisPrint.html',
    priority: 'P2',
    implemented: true,
    subtitle: '按物流单生成浏览器发货清单',
    componentKey: 'logisticsPrint',
    showCount: true,
    plannedComponent: 'features/logistics/LogisPrint.vue',
    coreActions: ['物流单查询', '发货清单打印', '本页合计'],
    apiDependencies: ['物流单查询'],
  },
  {
    key: 'logisticsMerges',
    label: '物流合并列表',
    group: '物流管理',
    path: '/logistics/merges',
    legacyRoute: 'logistics/listOrderMerge.html',
    priority: 'P2',
    implemented: true,
    subtitle: '合并发货和合单管理',
    componentKey: 'logisticsMerges',
    showCount: true,
    plannedComponent: 'features/logistics/OrderMergeList.vue',
    coreActions: ['合单列表', '合并', '删除合并'],
    apiDependencies: ['合单查询', '合单保存', '合单删除'],
  },
  {
    key: 'logisticsUnreceivedFollowups',
    label: '未签收跟进',
    group: '物流管理',
    path: '/logistics/unreceived-followups',
    legacyRoute: 'logistics/listUnreceiptedOrderInfo.html',
    priority: 'P2',
    implemented: true,
    subtitle: '超时未签收订单跟进',
    componentKey: 'logisticsUnreceivedFollowups',
    plannedComponent: 'features/logistics/UnreceivedFollowup.vue',
    coreActions: ['未签收筛选', '轨迹跟进', '手动签收'],
    apiDependencies: ['物流单查询', '物流轨迹', '签收接口'],
  },
  {
    key: 'orders',
    label: '处方列表',
    group: '订单管理',
    path: '/orders/prescriptions',
    legacyRoute: 'order/listOrder.html',
    priority: 'P1',
    implemented: true,
    subtitle: '查询订单详情、处方和履约进度',
    componentKey: 'orders',
    plannedComponent: 'features/orders/PrescriptionOrderList.vue',
    coreActions: ['列表', '筛选', '详情', '进度', '状态日志'],
    apiDependencies: ['订单分页', '订单详情', '处方明细', '进度'],
  },
  {
    key: 'reviews',
    label: '订单审核',
    group: '订单管理',
    path: '/orders/reviews',
    legacyRoute: 'order/listExamineOrder.html',
    priority: 'P1',
    implemented: true,
    subtitle: '处理待审核订单',
    componentKey: 'reviews',
    showCount: true,
    plannedComponent: 'features/workflow/ReviewTasks.vue',
    coreActions: ['审核任务', '通过', '驳回', '锁定'],
    apiDependencies: ['审核任务', '通过/驳回', '乐观锁'],
  },
  {
    key: 'dispenses',
    label: '调剂打印',
    group: '订单管理',
    path: '/orders/dispenses',
    legacyRoute: 'order/listAdjustOrder.html',
    priority: 'P1',
    implemented: true,
    subtitle: '处理待调剂处方任务',
    componentKey: 'dispensePrint',
    showCount: true,
    plannedComponent: 'features/workflow/DispensePrintWorkspace.vue',
    coreActions: ['调剂任务', '打印预览', '完成调剂/打印'],
    apiDependencies: ['调剂任务', '订单进度', '完成动作'],
  },
  {
    key: 'rechecks',
    label: '处方复核',
    group: '订单管理',
    path: '/orders/rechecks',
    legacyRoute: 'order/review.html',
    priority: 'P1',
    implemented: true,
    subtitle: '处理待复核处方任务',
    componentKey: 'recheckScan',
    showCount: true,
    plannedComponent: 'features/workflow/RecheckScanWorkspace.vue',
    coreActions: ['单桶复核', '完成', '异常处理'],
    apiDependencies: ['复核任务', '完成动作', '异常处理'],
  },
  {
    key: 'orderRechecksMulti',
    label: '处方复核（多桶）',
    group: '订单管理',
    path: '/orders/rechecks-multi',
    legacyRoute: 'order/reviews.html',
    priority: 'P1',
    implemented: true,
    subtitle: '多桶复核和批量确认',
    componentKey: 'recheckScan',
    showCount: true,
    plannedComponent: 'features/workflow/RecheckScanWorkspace.vue',
    coreActions: ['多桶复核', '批量确认'],
    apiDependencies: ['多桶复核任务', '绑定关系', '状态一致性校验'],
  },
  {
    key: 'orderRecheckRecords',
    label: '复核管理',
    group: '订单管理',
    path: '/orders/recheck-records',
    legacyRoute: 'order/listReview.html',
    priority: 'P1',
    implemented: true,
    subtitle: '复核记录查询和管理',
    componentKey: 'rechecks',
    showCount: true,
    plannedComponent: 'features/workflow/RecheckRecordList.vue',
    coreActions: ['复核记录查询', '导出'],
    apiDependencies: ['复核记录', '导出任务'],
  },
  {
    key: 'orderAddressModifications',
    label: '订单地址修改',
    group: '订单管理',
    path: '/orders/address-modifications',
    legacyRoute: 'order/listModifyAddress.html',
    priority: 'P1',
    implemented: true,
    subtitle: '收件地址维护和变更记录',
    componentKey: 'addressModify',
    plannedComponent: 'features/orders/AddressModify.vue',
    coreActions: ['单改', '批量改', '记录查询'],
    apiDependencies: ['地址修改', '地址变更记录', '批量导入预检'],
  },
  {
    key: 'orderPrescriptionModifications',
    label: '处方修改',
    group: '订单管理',
    path: '/orders/prescription-modifications',
    legacyRoute: 'order/listModifyPrescri.html',
    priority: 'P1',
    implemented: true,
    subtitle: '处方信息维护和重新校验',
    componentKey: 'prescriptionModify',
    plannedComponent: 'features/orders/PrescriptionModify.vue',
    coreActions: ['处方修改', '重新校验'],
    apiDependencies: ['处方修改', '校验事件'],
  },
  {
    key: 'orderManageActions',
    label: '订单操作',
    group: '订单管理',
    path: '/orders/manage-actions',
    legacyRoute: 'order/listManageOrder.html',
    priority: 'P1',
    implemented: true,
    subtitle: '取消、回退、补偿等管理动作',
    componentKey: 'orderManageAction',
    plannedComponent: 'features/orders/OrderManageAction.vue',
    coreActions: ['处方初始化', '取消处方', '操作审计'],
    apiDependencies: ['订单操作列表', '处方级初始化', '处方级取消', '操作审计'],
  },
  {
    key: 'orderPrescriptionReprints',
    label: '处方重打',
    group: '订单管理',
    path: '/orders/prescription-reprints',
    legacyRoute: 'order/listPrescriptionReprint.html',
    priority: 'P1',
    implemented: true,
    subtitle: '处方单据重打申请和打印记录',
    componentKey: 'prescriptionReprint',
    plannedComponent: 'features/orders/PrescriptionReprint.vue',
    coreActions: ['处方查询', '处方重打预览'],
    apiDependencies: ['处方重打列表', '处方打印数据'],
  },
  {
    key: 'orderWarehouse',
    label: '订单仓库',
    group: '订单管理',
    path: '/orders/warehouse',
    legacyRoute: 'order/listOrderWarehouse.html',
    priority: 'P2',
    implemented: true,
    subtitle: '仓库视角订单查询和导出',
    componentKey: 'orderWarehouse',
    plannedComponent: 'features/orders/OrderWarehouse.vue',
    coreActions: ['仓库视角查询', '导出'],
    apiDependencies: ['仓库订单查询', '导出任务'],
  },
  {
    key: 'orderInterceptRules',
    label: '订单拦截配置',
    group: '订单管理',
    path: '/orders/intercept-rules',
    legacyRoute: 'order/listFillpushPrescriptionsIntercept.html',
    priority: 'P2',
    implemented: true,
    subtitle: '推送和流转拦截规则配置',
    componentKey: 'orderInterceptRules',
    showCount: true,
    plannedComponent: 'features/orders/OrderInterceptRule.vue',
    coreActions: ['拦截规则新增', '编辑', '删除'],
    apiDependencies: ['拦截规则 CRUD', '操作审计'],
  },
  {
    key: 'orderManualProcess',
    label: '订单走流程',
    group: '订单管理',
    path: '/orders/manual-process',
    legacyRoute: 'order/listProcessOrder.html',
    priority: 'P1',
    implemented: true,
    subtitle: '手工推进流程和补齐数据',
    componentKey: 'manualProcess',
    plannedComponent: 'features/orders/ManualProcess.vue',
    coreActions: ['手工推进流程', '补齐数据'],
    apiDependencies: ['手工流程推进', '状态机', '操作审计'],
  },
  {
    key: 'orderReceipts',
    label: '订单签收',
    group: '订单管理',
    path: '/orders/receipts',
    legacyRoute: 'order/listOrderReceipt.html',
    priority: 'P1',
    implemented: true,
    subtitle: '签收确认和批量签收导入',
    componentKey: 'orderReceipt',
    plannedComponent: 'features/orders/OrderReceipt.vue',
    coreActions: ['手工签收', '批量签收导入'],
    apiDependencies: ['签收', '批量导入', '物流状态'],
  },
  {
    key: 'observability',
    label: '订单流程查询',
    group: '维护管理',
    path: '/maintenance/order-processes',
    legacyRoute: 'mainten/listOrderProcess.html',
    priority: 'P1',
    implemented: true,
    subtitle: '按订单聚合访问、状态、MQ、回调、死信和补偿证据',
    componentKey: 'observability',
    showCount: true,
    plannedComponent: 'features/ops/OrderProcessList.vue',
    coreActions: ['流程查询', '详情', '导出'],
    apiDependencies: ['订单流程', '处方流程', '操作日志'],
  },
  {
    key: 'maintenanceExceptionLogs',
    label: '异常日志信息查询',
    group: '维护管理',
    path: '/maintenance/exception-logs',
    legacyRoute: 'mainten/listLogException.html',
    priority: 'P4',
    implemented: true,
    subtitle: '查询死信、物流回调失败和集成失败事件',
    componentKey: 'exceptionLogs',
    showCount: true,
    plannedComponent: 'features/ops/ExceptionLogList.vue',
    coreActions: ['死信查询', '回调失败查询', '集成失败查询', '死信重放/关闭'],
    apiDependencies: ['死信记录', '物流回调失败', '集成重试失败'],
  },
  {
    key: 'ops',
    label: 'MQ 消息查询列表',
    group: '维护管理',
    path: '/maintenance/mq-messages',
    legacyRoute: 'mainten/listMqMessage.html',
    priority: 'P1',
    implemented: true,
    subtitle: '查询事件、消费、校验、访问和失败任务',
    componentKey: 'ops',
    showCount: true,
    plannedComponent: 'features/ops/MqMessageList.vue',
    coreActions: ['MQ 查询', '重试', '死信处理'],
    apiDependencies: ['Outbox', '消费日志', '死信', '重放'],
  },
  {
    key: 'maintenanceProblemRegistrations',
    label: '问题件登记',
    group: '维护管理',
    path: '/maintenance/problem-registrations',
    legacyRoute: 'mainten/listOrderProblemRegistration.html',
    priority: 'P4',
    implemented: true,
    subtitle: '问题订单登记与处理',
    componentKey: 'problemRegistrations',
    showCount: true,
    plannedComponent: 'features/ops/ProblemRegistration.vue',
    coreActions: ['新增', '编辑', '处理', '关闭', '导出'],
    apiDependencies: ['问题件 CRUD', '处理记录', '操作审计'],
  },
  {
    key: 'labelTemplates',
    label: '处方标签设置',
    group: '标签管理',
    path: '/labels/templates',
    legacyRoute: 'lable/listDecotingLableset.html',
    priority: 'P4',
    implemented: true,
    subtitle: '标签模板配置和预览',
    componentKey: 'labelTemplates',
    showCount: true,
    plannedComponent: 'features/label/LabelTemplate.vue',
    coreActions: ['模板列表', '新增', '编辑', '删除', '预览'],
    apiDependencies: ['标签模板 CRUD', '标签预览', '操作审计'],
  },
  {
    key: 'labelPrints',
    label: '处方标签打印',
    group: '标签管理',
    path: '/labels/prints',
    legacyRoute: 'lable/labelPrint.html?viewName=decotingLablePrint',
    priority: 'P4',
    implemented: true,
    subtitle: '按处方查询并生成浏览器处方标签',
    componentKey: 'labelPrints',
    showCount: true,
    plannedComponent: 'features/label/LabelPrint.vue',
    coreActions: ['处方查询', '标签预览', '浏览器打印'],
    apiDependencies: ['处方重打列表', '处方打印数据'],
  },
  {
    key: 'smsTemplates',
    label: '短信模板管理',
    group: '短信管理',
    path: '/sms/templates',
    legacyRoute: 'sms/listSmsMoudle.html',
    priority: 'P4',
    implemented: true,
    subtitle: '短信模板维护',
    componentKey: 'smsTemplates',
    showCount: true,
    plannedComponent: 'features/sms/SmsTemplate.vue',
    coreActions: ['模板列表', '新增', '编辑', '删除'],
    apiDependencies: ['短信模板 CRUD', '操作审计'],
  },
  {
    key: 'smsSendSingle',
    label: '单发短信',
    group: '短信管理',
    path: '/sms/send-single',
    legacyRoute: 'sms/sendUnitSmsInit.html',
    priority: 'P4',
    implemented: true,
    subtitle: '手工发送短信',
    componentKey: 'smsSendSingle',
    plannedComponent: 'features/sms/SingleSmsSend.vue',
    coreActions: ['选择模板', '录入号码', '发送'],
    apiDependencies: ['单发短信', '余额查询', '发送记录'],
  },
  {
    key: 'smsRecords',
    label: '短信列表查询',
    group: '短信管理',
    path: '/sms/records',
    legacyRoute: 'sms/listSms.html',
    priority: 'P4',
    implemented: true,
    subtitle: '短信发送记录查询和失败重试',
    componentKey: 'smsRecords',
    showCount: true,
    plannedComponent: 'features/sms/SmsRecordList.vue',
    coreActions: ['发送记录', '详情', '失败重试'],
    apiDependencies: ['短信记录', '重试接口'],
  },
  {
    key: 'drugHerbs',
    label: '药品目录列表',
    group: '药品管理',
    path: '/drugs/herbs',
    legacyRoute: 'drugManage/listHerbs.html',
    priority: 'P3',
    implemented: true,
    subtitle: '药品主数据维护',
    componentKey: 'drugHerbs',
    showCount: true,
    plannedComponent: 'features/drug/HerbList.vue',
    coreActions: ['列表', '新增', '编辑', '启停', '导出'],
    apiDependencies: ['药品 CRUD', '导出任务', '操作日志'],
  },
  {
    key: 'drugIndexOperationLogs',
    label: '药品索引操作日志',
    group: '药品管理',
    path: '/drugs/index-operation-logs',
    legacyRoute: 'drugManage/listImportantOperLog.html',
    priority: 'P3',
    implemented: true,
    subtitle: '药品索引变更审计',
    componentKey: 'drugIndexOperationLogs',
    showCount: true,
    plannedComponent: 'features/drug/HerbIndexOperationLog.vue',
    coreActions: ['操作日志查询', '导出'],
    apiDependencies: ['索引操作日志', '导出任务'],
  },
  {
    key: 'drugHerbIndexes',
    label: '药品索引列表',
    group: '药品管理',
    path: '/drugs/herb-indexes',
    legacyRoute: 'drugManage/listHerbsIndex.html',
    priority: 'P3',
    implemented: true,
    subtitle: '药品匹配索引维护',
    componentKey: 'drugHerbIndexes',
    showCount: true,
    plannedComponent: 'features/drug/HerbIndexList.vue',
    coreActions: ['索引列表', '新增', '编辑', '启停'],
    apiDependencies: ['药品索引 CRUD', '重复检查'],
  },
  {
    key: 'drugHerbImports',
    label: '药品目录导入',
    group: '药品管理',
    path: '/drugs/herbs/imports',
    legacyRoute: 'drugManage/importHerbsInit.html',
    priority: 'P3',
    implemented: false,
    subtitle: '药品批量导入',
    plannedComponent: 'features/drug/HerbImport.vue',
    coreActions: ['模板下载', '导入', '错误明细'],
    apiDependencies: ['导入任务', '导入预检', '错误下载'],
  },
  {
    key: 'drugHerbIndexImports',
    label: '药品索引导入',
    group: '药品管理',
    path: '/drugs/herb-indexes/imports',
    legacyRoute: 'drugManage/importHerbsIndexInit.html',
    priority: 'P3',
    implemented: false,
    subtitle: '索引批量导入',
    plannedComponent: 'features/drug/HerbIndexImport.vue',
    coreActions: ['模板下载', '导入', '错误明细'],
    apiDependencies: ['索引导入任务', '重复检查', '错误下载'],
  },
  {
    key: 'drugHerbAreas',
    label: '药材区域管理',
    group: '药品管理',
    path: '/drugs/herb-areas',
    legacyRoute: 'drugManage/listHerbsArea.html',
    priority: 'P3',
    implemented: true,
    subtitle: '药材区域配置',
    componentKey: 'drugHerbAreas',
    showCount: true,
    plannedComponent: 'features/drug/HerbAreaManage.vue',
    coreActions: ['列表', '新增', '编辑', '启停'],
    apiDependencies: ['药材区域 CRUD'],
  },
  {
    key: 'reports',
    label: '处方数量统计',
    group: '报表管理',
    path: '/reports/prescription-counts',
    legacyRoute: 'exportQuery/prescriptionNumStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '查看核心指标、状态分布和趋势导出',
    componentKey: 'reports',
    showCount: true,
    plannedComponent: 'features/report/PrescriptionCountReport.vue',
    coreActions: ['汇总', '趋势', '导出'],
    apiDependencies: ['处方数量统计', '导出任务'],
  },
  {
    key: 'reportInstitutionPrescriptionCounts',
    label: '机构处方数量统计',
    group: '报表管理',
    path: '/reports/institution-prescription-counts',
    legacyRoute: 'exportQuery/institutionsPrescriptionNumStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '机构维度处方量统计',
    componentKey: 'institutionPrescriptionCounts',
    showCount: true,
    plannedComponent: 'features/reports/InstitutionPrescriptionCounts.vue',
    coreActions: ['机构处方数量查询', '本页小计', 'CSV 导出'],
    apiDependencies: ['机构处方数量统计', '机构处方数量 CSV 导出'],
  },
  {
    key: 'reportAuditPerformance',
    label: '审核员业绩统计',
    group: '报表管理',
    path: '/reports/audit-performance',
    legacyRoute: 'exportQuery/auditPerformanceStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '审核员绩效汇总',
    componentKey: 'auditPerformance',
    showCount: true,
    plannedComponent: 'features/reports/AuditPerformance.vue',
    coreActions: ['审核员绩效查询', '通过驳回统计', 'CSV 导出'],
    apiDependencies: ['审核绩效统计', '审核绩效 CSV 导出'],
  },
  {
    key: 'reportAuditPerformanceDetails',
    label: '审核员业绩明细',
    group: '报表管理',
    path: '/reports/audit-performance-details',
    legacyRoute: 'exportQuery/auditPerformanceDetail.html',
    priority: 'P4',
    implemented: true,
    subtitle: '审核员绩效明细',
    componentKey: 'auditPerformanceDetails',
    showCount: true,
    plannedComponent: 'features/reports/AuditPerformanceDetails.vue',
    coreActions: ['审核明细查询', '通过驳回明细', 'CSV 导出'],
    apiDependencies: ['审核绩效明细', '审核绩效明细 CSV 导出'],
  },
  {
    key: 'reportDispensePerformance',
    label: '调剂员业绩统计',
    group: '报表管理',
    path: '/reports/dispense-performance',
    legacyRoute: 'exportQuery/dispensePerformanceStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '调剂员绩效汇总',
    componentKey: 'dispensePerformance',
    showCount: true,
    plannedComponent: 'features/reports/DispensePerformance.vue',
    coreActions: ['调剂员绩效查询', '汇总小计', 'CSV 导出'],
    apiDependencies: ['调剂绩效统计', '调剂绩效 CSV 导出'],
  },
  {
    key: 'reportDispensePerformanceDetails',
    label: '调剂员业绩明细',
    group: '报表管理',
    path: '/reports/dispense-performance-details',
    legacyRoute: 'exportQuery/dispensePerformanceDetail.html',
    priority: 'P4',
    implemented: true,
    subtitle: '调剂员绩效明细',
    componentKey: 'dispensePerformanceDetails',
    showCount: true,
    plannedComponent: 'features/reports/DispensePerformanceDetails.vue',
    coreActions: ['明细', '导出'],
    apiDependencies: ['调剂绩效明细', '异步导出任务'],
  },
  {
    key: 'reportRecheckPerformance',
    label: '复核员业绩统计',
    group: '报表管理',
    path: '/reports/recheck-performance',
    legacyRoute: 'exportQuery/recheckPerformanceStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '复核员绩效汇总',
    componentKey: 'recheckPerformance',
    showCount: true,
    plannedComponent: 'features/reports/RecheckPerformance.vue',
    coreActions: ['复核员绩效查询', '汇总小计', 'CSV 导出'],
    apiDependencies: ['复核绩效统计', '复核绩效 CSV 导出'],
  },
  {
    key: 'reportRecheckPerformanceDetails',
    label: '复核员业绩明细',
    group: '报表管理',
    path: '/reports/recheck-performance-details',
    legacyRoute: 'exportQuery/recheckPerformanceDetail.html',
    priority: 'P4',
    implemented: true,
    subtitle: '复核员绩效明细',
    componentKey: 'recheckPerformanceDetails',
    showCount: true,
    plannedComponent: 'features/reports/RecheckPerformanceDetails.vue',
    coreActions: ['明细', '导出'],
    apiDependencies: ['复核绩效明细', '人员筛选', '异步导出任务'],
  },
  {
    key: 'reportDecoctionPerformance',
    label: '煎煮员业绩统计',
    group: '报表管理',
    path: '/reports/decoction-performance',
    legacyRoute: 'exportQuery/boilPerformanceStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '煎煮员绩效汇总',
    componentKey: 'decoctionPerformance',
    showCount: true,
    plannedComponent: 'features/reports/DecoctionPerformance.vue',
    coreActions: ['煎煮员绩效查询', '设备数统计', 'CSV 导出'],
    apiDependencies: ['煎煮绩效统计', '煎煮绩效 CSV 导出'],
  },
  {
    key: 'reportDecoctionPerformanceDetails',
    label: '煎煮员业绩明细',
    group: '报表管理',
    path: '/reports/decoction-performance-details',
    legacyRoute: 'exportQuery/boilPerformanceDetail.html',
    priority: 'P4',
    implemented: true,
    subtitle: '煎煮员绩效明细',
    componentKey: 'decoctionPerformanceDetails',
    showCount: true,
    plannedComponent: 'features/reports/DecoctionPerformanceDetails.vue',
    coreActions: ['明细', '导出'],
    apiDependencies: ['煎煮绩效明细', '设备作业记录', '异步导出任务'],
  },
  {
    key: 'reportLogisticsPerformance',
    label: '物流员业绩统计',
    group: '报表管理',
    path: '/reports/logistics-performance',
    legacyRoute: 'exportQuery/packagePerformanceStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '物流员绩效汇总',
    componentKey: 'logisticsPerformance',
    showCount: true,
    plannedComponent: 'features/reports/LogisticsPerformance.vue',
    coreActions: ['物流绩效查询', '汇总小计', 'CSV 导出'],
    apiDependencies: ['物流绩效统计', '物流绩效 CSV 导出'],
  },
  {
    key: 'reportLogisticsPerformanceDetails',
    label: '物流员业绩明细',
    group: '报表管理',
    path: '/reports/logistics-performance-details',
    legacyRoute: 'exportQuery/packagePerformanceDetail.html',
    priority: 'P4',
    implemented: true,
    subtitle: '物流员绩效明细',
    componentKey: 'logisticsPerformanceDetails',
    showCount: true,
    plannedComponent: 'features/reports/LogisticsPerformanceDetails.vue',
    coreActions: ['明细查询', '汇总小计', 'CSV 导出'],
    apiDependencies: ['物流绩效明细', '物流绩效明细 CSV 导出'],
  },
  {
    key: 'reportInstitutionHerbReconciliation',
    label: '机构药材统计（对账）',
    group: '报表管理',
    path: '/reports/institution-herb-reconciliation',
    legacyRoute: 'exportQuery/orgHerbsStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '机构药材对账汇总',
    componentKey: 'institutionHerbReconciliation',
    showCount: true,
    plannedComponent: 'features/reports/InstitutionHerbReconciliation.vue',
    coreActions: ['机构药材查询', '数量金额汇总', 'CSV 导出'],
    apiDependencies: ['机构药材统计', '机构药材 CSV 导出'],
  },
  {
    key: 'reportPrescriptionReconciliation',
    label: '处方对账列表（对账）',
    group: '报表管理',
    path: '/reports/prescription-reconciliation',
    legacyRoute: 'exportQuery/prescriAccount.html',
    priority: 'P4',
    implemented: true,
    subtitle: '按订单处方明细查询金额和配送对账字段',
    componentKey: 'prescriptionReconciliation',
    showCount: true,
    plannedComponent: 'features/reports/PrescriptionReconciliation.vue',
    coreActions: ['处方对账查询', '本页小计', 'CSV 导出'],
    apiDependencies: ['订单分页查询', '订单 CSV 导出'],
  },
  {
    key: 'reportPrescriptionHerbDetails',
    label: '药材明细列表（对账）',
    group: '报表管理',
    path: '/reports/prescription-herb-details',
    legacyRoute: 'exportQuery/prescriHerbsDetail.html',
    priority: 'P4',
    implemented: true,
    subtitle: '药材明细对账',
    componentKey: 'prescriptionHerbDetails',
    showCount: true,
    plannedComponent: 'features/reports/PrescriptionHerbDetails.vue',
    coreActions: ['药材明细查询', '金额字段展示', 'CSV 导出'],
    apiDependencies: ['药材明细查询', '药材明细 CSV 导出'],
  },
  {
    key: 'reportHerbDosage',
    label: '药材用量统计',
    group: '报表管理',
    path: '/reports/herb-dosage',
    legacyRoute: 'exportQuery/medicinalDoseStatistics.html',
    priority: 'P4',
    implemented: true,
    subtitle: '药材消耗统计',
    componentKey: 'herbDosage',
    showCount: true,
    plannedComponent: 'features/reports/HerbDosage.vue',
    coreActions: ['药材用量查询', '数量金额汇总', 'CSV 导出'],
    apiDependencies: ['药材用量统计', '药材用量 CSV 导出'],
  },
  {
    key: 'decoction',
    label: '设备列表查询',
    group: '煎煮管理',
    path: '/decoction/equipment',
    legacyRoute: 'decoct/listEquipmentManage.html',
    priority: 'P2',
    implemented: true,
    subtitle: '处理处方绑定、煎煮状态和设备作业记录',
    componentKey: 'decoction',
    showCount: true,
    plannedComponent: 'features/decoction/DecoctionWorkspace.vue',
    coreActions: ['设备列表', '作业状态', '事件记录'],
    apiDependencies: ['设备列表', '活动任务', '作业记录'],
  },
  {
    key: 'decoctionPrescriptionBindings',
    label: '处方设备绑定列表',
    group: '煎煮管理',
    path: '/decoction/prescription-bindings',
    legacyRoute: 'decoct/listPrescriptionBindInfo.html',
    priority: 'P2',
    implemented: true,
    subtitle: '处方和设备绑定记录查询',
    componentKey: 'decoction',
    showCount: true,
    plannedComponent: 'features/decoction/DecoctionWorkspace.vue',
    coreActions: ['可操作处方', '绑定设备/水桶', '加水/开始/完成'],
    apiDependencies: ['可操作处方', '设备列表', '绑定处方', 'MES 作业动作'],
  },
  {
    key: 'decoctionPdaPrinterRelations',
    label: '打码机打印配置',
    group: '煎煮管理',
    path: '/decoction/pda-printer-relations',
    legacyRoute: 'decoct/listPdaDmjRelation.html',
    priority: 'P2',
    implemented: true,
    subtitle: 'PDA 和打码机关系配置',
    componentKey: 'decoction',
    plannedComponent: 'features/decoction/DecoctionWorkspace.vue',
    coreActions: ['PDA/打码机配置入口', '配置缺口提示'],
    apiDependencies: ['关系 CRUD 待补', '操作审计待补'],
  },
  {
    key: 'decoctionWaterPails',
    label: '加水桶管理',
    group: '煎煮管理',
    path: '/decoction/water-pails',
    legacyRoute: 'decoct/listWaterpailInfo.html',
    priority: 'P2',
    implemented: true,
    subtitle: '加水桶列表和批量新增',
    componentKey: 'decoction',
    plannedComponent: 'features/decoction/DecoctionWorkspace.vue',
    coreActions: ['加水桶管理入口', '批量新增缺口提示', '导出缺口提示'],
    apiDependencies: ['加水桶 CRUD 待补', '导出任务待补'],
  },
  {
    key: 'decoctionCloudPrintRecords',
    label: '云打印记录列表',
    group: '煎煮管理',
    path: '/decoction/cloud-print-records',
    legacyRoute: 'decoct/listBqPrintRecord.html',
    priority: 'P2',
    implemented: true,
    subtitle: '云打印记录、失败重试和重打',
    componentKey: 'decoction',
    plannedComponent: 'features/decoction/DecoctionWorkspace.vue',
    coreActions: ['云打印记录入口', '补打缺口提示'],
    apiDependencies: ['打印记录待补', '重试接口待补', '重打记录待补'],
  },
] as const satisfies readonly MenuItem[];

export const routeItems = [...standaloneRouteItems, ...menuItems] as const;

export type ViewKey = (typeof routeItems)[number]['key'];
export type RouteKey = ViewKey;

export const routeByKey = routeItems.reduce((map, item) => {
  map[item.key as ViewKey] = item;
  return map;
}, {} as Record<ViewKey, AppRouteItem>);

export const viewTitles = routeItems.reduce((map, item) => {
  map[item.key as ViewKey] = { title: item.label, subtitle: item.subtitle };
  return map;
}, {} as Record<ViewKey, ViewTitle>);

export function isViewKey(value: string): value is ViewKey {
  return Object.prototype.hasOwnProperty.call(routeByKey, value);
}
