export interface AdminMenuItem {
  key: string;
  label: string;
  path: string;
  legacyRoute: string;
  title: string;
  parentKey: string;
  parentLabel: string;
  implemented: boolean;
}

export interface AdminMenuGroup {
  key: string;
  label: string;
  children: AdminMenuItem[];
}

export const menuGroups: AdminMenuGroup[] = [
  {
    key: 'system',
    label: '系统管理',
    children: [
      {
        key: 'system-users',
        label: '用户管理',
        path: '/system/users',
        legacyRoute: 'user.html',
        title: '用户管理',
        parentKey: 'system',
        parentLabel: '系统管理',
        implemented: true,
      },
      {
        key: 'system-roles',
        label: '角色管理',
        path: '/system/roles',
        legacyRoute: 'role.html',
        title: '角色管理',
        parentKey: 'system',
        parentLabel: '系统管理',
        implemented: true,
      },
      {
        key: 'system-menus',
        label: '菜单管理',
        path: '/system/menus',
        legacyRoute: 'menu.html',
        title: '菜单管理',
        parentKey: 'system',
        parentLabel: '系统管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'settings',
    label: '参数管理',
    children: [
      {
        key: 'settings-dicts',
        label: '字典列表',
        path: '/settings/dicts',
        legacyRoute: 'systemSetting/listDict.html',
        title: '字典列表',
        parentKey: 'settings',
        parentLabel: '参数管理',
        implemented: true,
      },
      {
        key: 'settings-configs',
        label: '参数配置',
        path: '/settings/system-configs',
        legacyRoute: 'systemSetting/listSystemConfig.html',
        title: '参数配置',
        parentKey: 'settings',
        parentLabel: '参数管理',
        implemented: true,
      },
      {
        key: 'settings-decoct-centers',
        label: '煎煮中心配置',
        path: '/settings/decoct-centers',
        legacyRoute: 'systemSetting/listDecoctCenter.html',
        title: '煎煮中心配置',
        parentKey: 'settings',
        parentLabel: '参数管理',
        implemented: true,
      },
      {
        key: 'settings-operators',
        label: '工号管理',
        path: '/settings/operators',
        legacyRoute: 'systemSetting/listOperUser.html',
        title: '工号管理',
        parentKey: 'settings',
        parentLabel: '参数管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'institutions',
    label: '机构管理',
    children: [
      {
        key: 'institutions-list',
        label: '机构列表',
        path: '/institutions',
        legacyRoute: 'mechanism/listInstitutions.html',
        title: '机构列表',
        parentKey: 'institutions',
        parentLabel: '机构管理',
        implemented: true,
      },
      {
        key: 'institutions-ip',
        label: '机构 IP 白名单列表',
        path: '/institutions/ip-whitelist',
        legacyRoute: 'mechanism/listWhiteIp.html',
        title: '机构 IP 白名单列表',
        parentKey: 'institutions',
        parentLabel: '机构管理',
        implemented: true,
      },
      {
        key: 'institutions-apis',
        label: '接口列表',
        path: '/institutions/apis',
        legacyRoute: 'mechanism/listApiInfo.html',
        title: '接口列表',
        parentKey: 'institutions',
        parentLabel: '机构管理',
        implemented: true,
      },
      {
        key: 'institutions-api-permissions',
        label: '机构接口权限列表',
        path: '/institutions/api-permissions',
        legacyRoute: 'mechanism/listApiPermission.html',
        title: '机构接口权限列表',
        parentKey: 'institutions',
        parentLabel: '机构管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'logistics',
    label: '物流管理',
    children: [
      {
        key: 'logistics-special-rules',
        label: '机构物流费规则配置',
        path: '/logistics/special-rules',
        legacyRoute: 'logistics/listLogisSpecial.html',
        title: '机构物流费规则配置',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: true,
      },
      {
        key: 'logistics-address-costs',
        label: '机构地址物流费配置',
        path: '/logistics/address-costs',
        legacyRoute: 'logistics/listLogisCompanycostAddr.html',
        title: '机构地址物流费配置',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: true,
      },
      {
        key: 'logistics-delivery',
        label: '订单发货查询',
        path: '/logistics/deliveries',
        legacyRoute: 'logistics/listLogisDelivery.html',
        title: '订单发货查询',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: true,
      },
      {
        key: 'logistics-info',
        label: '物流信息查询',
        path: '/logistics/infos',
        legacyRoute: 'logistics/listLogisInfo.html',
        title: '物流信息查询',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: true,
      },
      {
        key: 'logistics-print',
        label: '物流打单',
        path: '/logistics/print',
        legacyRoute: 'logistics/logisPrint.html',
        title: '物流打单',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: false,
      },
      {
        key: 'logistics-merges',
        label: '物流合并列表',
        path: '/logistics/merges',
        legacyRoute: 'logistics/listOrderMerge.html',
        title: '物流合并列表',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: true,
      },
      {
        key: 'logistics-unreceived',
        label: '未签收跟进',
        path: '/logistics/unreceived-followups',
        legacyRoute: 'logistics/listUnreceiptedOrderInfo.html',
        title: '未签收跟进',
        parentKey: 'logistics',
        parentLabel: '物流管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'orders',
    label: '订单管理',
    children: [
      {
        key: 'orders-prescriptions',
        label: '处方列表',
        path: '/orders/prescriptions',
        legacyRoute: 'order/listOrder.html',
        title: '处方列表',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
      {
        key: 'orders-audit',
        label: '订单审核',
        path: '/orders/audit',
        legacyRoute: 'order/listExamineOrder.html',
        title: '订单审核',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-dispense',
        label: '调剂打印',
        path: '/orders/dispense',
        legacyRoute: 'order/listAdjustOrder.html',
        title: '调剂打印',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
      {
        key: 'orders-recheck',
        label: '处方复核',
        path: '/orders/recheck',
        legacyRoute: 'order/review.html',
        title: '处方复核',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
      {
        key: 'orders-recheck-multi',
        label: '处方复核（多桶）',
        path: '/orders/recheck-multi',
        legacyRoute: 'order/reviews.html',
        title: '处方复核（多桶）',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
      {
        key: 'orders-recheck-records',
        label: '复核管理',
        path: '/orders/recheck-records',
        legacyRoute: 'order/listReview.html',
        title: '复核管理',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-address',
        label: '订单地址修改',
        path: '/orders/address-modifications',
        legacyRoute: 'order/listModifyAddress.html',
        title: '订单地址修改',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-prescription-modify',
        label: '处方修改',
        path: '/orders/prescription-modifications',
        legacyRoute: 'order/listModifyPrescri.html',
        title: '处方修改',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-actions',
        label: '订单操作',
        path: '/orders/manage-actions',
        legacyRoute: 'order/listManageOrder.html',
        title: '订单操作',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
      {
        key: 'orders-reprint',
        label: '处方重打',
        path: '/orders/prescription-reprints',
        legacyRoute: 'order/listPrescriptionReprint.html',
        title: '处方重打',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-warehouse',
        label: '订单仓库',
        path: '/orders/warehouse',
        legacyRoute: 'order/listOrderWarehouse.html',
        title: '订单仓库',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-intercept',
        label: '订单拦截配置',
        path: '/orders/intercept-rules',
        legacyRoute: 'order/listFillpushPrescriptionsIntercept.html',
        title: '订单拦截配置',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: true,
      },
      {
        key: 'orders-manual-process',
        label: '订单走流程',
        path: '/orders/manual-process',
        legacyRoute: 'order/listProcessOrder.html',
        title: '订单走流程',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
      {
        key: 'orders-receipts',
        label: '订单签收',
        path: '/orders/receipts',
        legacyRoute: 'order/listOrderReceipt.html',
        title: '订单签收',
        parentKey: 'orders',
        parentLabel: '订单管理',
        implemented: false,
      },
    ],
  },
  {
    key: 'maintenance',
    label: '维护管理',
    children: [
      {
        key: 'maintenance-order-processes',
        label: '订单流程查询',
        path: '/maintenance/order-processes',
        legacyRoute: 'mainten/listOrderProcess.html',
        title: '订单流程查询',
        parentKey: 'maintenance',
        parentLabel: '维护管理',
        implemented: true,
      },
      {
        key: 'maintenance-exception-logs',
        label: '异常日志信息查询',
        path: '/maintenance/exception-logs',
        legacyRoute: 'mainten/listLogException.html',
        title: '异常日志信息查询',
        parentKey: 'maintenance',
        parentLabel: '维护管理',
        implemented: true,
      },
      {
        key: 'maintenance-mq',
        label: 'MQ 消息查询列表',
        path: '/maintenance/mq-messages',
        legacyRoute: 'mainten/listMqMessage.html',
        title: 'MQ 消息查询列表',
        parentKey: 'maintenance',
        parentLabel: '维护管理',
        implemented: true,
      },
      {
        key: 'maintenance-problems',
        label: '问题件登记',
        path: '/maintenance/problem-registrations',
        legacyRoute: 'mainten/listOrderProblemRegistration.html',
        title: '问题件登记',
        parentKey: 'maintenance',
        parentLabel: '维护管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'labels',
    label: '标签管理',
    children: [
      {
        key: 'labels-template',
        label: '处方标签设置',
        path: '/labels/templates',
        legacyRoute: 'lable/listDecotingLableset.html',
        title: '处方标签设置',
        parentKey: 'labels',
        parentLabel: '标签管理',
        implemented: true,
      },
      {
        key: 'labels-print',
        label: '处方标签打印',
        path: '/labels/prints',
        legacyRoute: 'lable/labelPrint.html?viewName=decotingLablePrint',
        title: '处方标签打印',
        parentKey: 'labels',
        parentLabel: '标签管理',
        implemented: false,
      },
    ],
  },
  {
    key: 'sms',
    label: '短信管理',
    children: [
      {
        key: 'sms-templates',
        label: '短信模板管理',
        path: '/sms/templates',
        legacyRoute: 'sms/listSmsMoudle.html',
        title: '短信模板管理',
        parentKey: 'sms',
        parentLabel: '短信管理',
        implemented: true,
      },
      {
        key: 'sms-send-single',
        label: '单发短信',
        path: '/sms/send-single',
        legacyRoute: 'sms/sendUnitSmsInit.html',
        title: '单发短信',
        parentKey: 'sms',
        parentLabel: '短信管理',
        implemented: true,
      },
      {
        key: 'sms-records',
        label: '短信列表查询',
        path: '/sms/records',
        legacyRoute: 'sms/listSms.html',
        title: '短信列表查询',
        parentKey: 'sms',
        parentLabel: '短信管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'drugs',
    label: '药品管理',
    children: [
      {
        key: 'drugs-herbs',
        label: '药品目录列表',
        path: '/drugs/herbs',
        legacyRoute: 'drugManage/listHerbs.html',
        title: '药品目录列表',
        parentKey: 'drugs',
        parentLabel: '药品管理',
        implemented: true,
      },
      {
        key: 'drugs-index-logs',
        label: '药品索引操作日志',
        path: '/drugs/index-operation-logs',
        legacyRoute: 'drugManage/listImportantOperLog.html',
        title: '药品索引操作日志',
        parentKey: 'drugs',
        parentLabel: '药品管理',
        implemented: true,
      },
      {
        key: 'drugs-indexes',
        label: '药品索引列表',
        path: '/drugs/herb-indexes',
        legacyRoute: 'drugManage/listHerbsIndex.html',
        title: '药品索引列表',
        parentKey: 'drugs',
        parentLabel: '药品管理',
        implemented: true,
      },
      {
        key: 'drugs-herbs-import',
        label: '药品目录导入',
        path: '/drugs/herbs/imports',
        legacyRoute: 'drugManage/importHerbsInit.html',
        title: '药品目录导入',
        parentKey: 'drugs',
        parentLabel: '药品管理',
        implemented: true,
      },
      {
        key: 'drugs-index-import',
        label: '药品索引导入',
        path: '/drugs/herb-indexes/imports',
        legacyRoute: 'drugManage/importHerbsIndexInit.html',
        title: '药品索引导入',
        parentKey: 'drugs',
        parentLabel: '药品管理',
        implemented: true,
      },
      {
        key: 'drugs-areas',
        label: '药材区域管理',
        path: '/drugs/herb-areas',
        legacyRoute: 'drugManage/listHerbsArea.html',
        title: '药材区域管理',
        parentKey: 'drugs',
        parentLabel: '药品管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'reports',
    label: '报表管理',
    children: [
      {
        key: 'reports-prescription-counts',
        label: '处方数量统计',
        path: '/reports/prescription-counts',
        legacyRoute: 'exportQuery/prescriptionNumStatistics.html',
        title: '处方数量统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-institution-counts',
        label: '机构处方数量统计',
        path: '/reports/institution-prescription-counts',
        legacyRoute: 'exportQuery/institutionsPrescriptionNumStatistics.html',
        title: '机构处方数量统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-audit-performance',
        label: '审核员业绩统计',
        path: '/reports/audit-performance',
        legacyRoute: 'exportQuery/auditPerformanceStatistics.html',
        title: '审核员业绩统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-audit-details',
        label: '审核员业绩明细',
        path: '/reports/audit-performance-details',
        legacyRoute: 'exportQuery/auditPerformanceDetail.html',
        title: '审核员业绩明细',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-dispense-performance',
        label: '调剂员业绩统计',
        path: '/reports/dispense-performance',
        legacyRoute: 'exportQuery/dispensePerformanceStatistics.html',
        title: '调剂员业绩统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-dispense-details',
        label: '调剂员业绩明细',
        path: '/reports/dispense-performance-details',
        legacyRoute: 'exportQuery/dispensePerformanceDetail.html',
        title: '调剂员业绩明细',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-recheck-performance',
        label: '复核员业绩统计',
        path: '/reports/recheck-performance',
        legacyRoute: 'exportQuery/recheckPerformanceStatistics.html',
        title: '复核员业绩统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-recheck-details',
        label: '复核员业绩明细',
        path: '/reports/recheck-performance-details',
        legacyRoute: 'exportQuery/recheckPerformanceDetail.html',
        title: '复核员业绩明细',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-decoction-performance',
        label: '煎煮员业绩统计',
        path: '/reports/decoction-performance',
        legacyRoute: 'exportQuery/boilPerformanceStatistics.html',
        title: '煎煮员业绩统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-decoction-details',
        label: '煎煮员业绩明细',
        path: '/reports/decoction-performance-details',
        legacyRoute: 'exportQuery/boilPerformanceDetail.html',
        title: '煎煮员业绩明细',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-logistics-performance',
        label: '物流员业绩统计',
        path: '/reports/logistics-performance',
        legacyRoute: 'exportQuery/packagePerformanceStatistics.html',
        title: '物流员业绩统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-logistics-details',
        label: '物流员业绩明细',
        path: '/reports/logistics-performance-details',
        legacyRoute: 'exportQuery/packagePerformanceDetail.html',
        title: '物流员业绩明细',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-org-herbs',
        label: '机构药材统计（对账）',
        path: '/reports/institution-herb-reconciliation',
        legacyRoute: 'exportQuery/orgHerbsStatistics.html',
        title: '机构药材统计（对账）',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-prescription-reconciliation',
        label: '处方对账列表（对账）',
        path: '/reports/prescription-reconciliation',
        legacyRoute: 'exportQuery/prescriAccount.html',
        title: '处方对账列表（对账）',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-herb-details',
        label: '药材明细列表（对账）',
        path: '/reports/prescription-herb-details',
        legacyRoute: 'exportQuery/prescriHerbsDetail.html',
        title: '药材明细列表（对账）',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
      {
        key: 'reports-herb-dosage',
        label: '药材用量统计',
        path: '/reports/herb-dosage',
        legacyRoute: 'exportQuery/medicinalDoseStatistics.html',
        title: '药材用量统计',
        parentKey: 'reports',
        parentLabel: '报表管理',
        implemented: true,
      },
    ],
  },
  {
    key: 'decoction',
    label: '煎煮管理',
    children: [
      {
        key: 'decoction-equipment',
        label: '设备列表查询',
        path: '/decoction/equipment',
        legacyRoute: 'decoct/listEquipmentManage.html',
        title: '设备列表查询',
        parentKey: 'decoction',
        parentLabel: '煎煮管理',
        implemented: true,
      },
      {
        key: 'decoction-bindings',
        label: '处方设备绑定列表',
        path: '/decoction/prescription-bindings',
        legacyRoute: 'decoct/listPrescriptionBindInfo.html',
        title: '处方设备绑定列表',
        parentKey: 'decoction',
        parentLabel: '煎煮管理',
        implemented: false,
      },
      {
        key: 'decoction-printers',
        label: '打码机打印配置',
        path: '/decoction/pda-printer-relations',
        legacyRoute: 'decoct/listPdaDmjRelation.html',
        title: '打码机打印配置',
        parentKey: 'decoction',
        parentLabel: '煎煮管理',
        implemented: true,
      },
      {
        key: 'decoction-water-pails',
        label: '加水桶管理',
        path: '/decoction/water-pails',
        legacyRoute: 'decoct/listWaterpailInfo.html',
        title: '加水桶管理',
        parentKey: 'decoction',
        parentLabel: '煎煮管理',
        implemented: true,
      },
      {
        key: 'decoction-cloud-prints',
        label: '云打印记录列表',
        path: '/decoction/cloud-print-records',
        legacyRoute: 'decoct/listBqPrintRecord.html',
        title: '云打印记录列表',
        parentKey: 'decoction',
        parentLabel: '煎煮管理',
        implemented: true,
      },
    ],
  },
];

export const menuItems = menuGroups.flatMap((group) => group.children);

export function findMenuItemByPath(pathname: string) {
  return menuItems.find((item) => item.path === pathname) ?? menuItems[0];
}
